version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: payload-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  payload:
    image: node:18
    container_name: payload-app
    working_dir: /app
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: sh -c "yarn install && yarn dev"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/payload
      - PAYLOAD_SECRET=dev-secret-key
      - NODE_ENV=development

volumes:
  mongo-data:
