version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: payload-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      # Map to 27018 on the host to avoid conflicts with local MongoDB
      - "27018:27017"

  payload:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payload-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "2501:3000"
    depends_on:
      - mongo
    environment:
      NODE_ENV: production

volumes:
  mongo-data:
